# Sample .travis.yml for R projects

dist: trusty
sudo: required

language: r
warnings_are_errors: true

r_github_packages:
  - MartinRoth/visDec
r_packages:
  - covr
after_success:
  - Rscript -e 'covr::codecov()'

